### ISSUE TITLE
How to use this code to attack VGG16?

### ISSUE THREAD

**Issue by tuji-sjp** [Hyperparticle/one-pixel-attack-keras#11]
Hello, could you please tell me about how to use? Thank you!

**Comment by Hyperparticle** [comment]
It should be straightforward to use VGG16. I included a `vgg16.py` file, which you can train. Alternatively, you can use Keras's pretrained model: https://keras.io/applications/#vgg16

Then it should be as simple as including it in the list of models. Let me know if you have any difficulty.

**Comment by Hyperparticle** [comment]
Are you still working on this?

**Comment by tuji-sjp** [comment]
> Are you still working on this?

Oh, yes. I'm so sorry. Running statistics result is a bit slow.
And how do I use the GPU to accelerate this process?

**Comment by Hyperparticle** [comment]
You should have CUDA, CuDNN, and `tensorflow-gpu` installed on your system. Then the library should automatically detect and use your GPU if it is available. To detect if the library is using GPU, see #9.

Alternatively, you can use [Google Colab](https://colab.research.google.com/drive/1Zq1kGP9C7i-70-SXyuEEaqYngtyQZMn7) to run the notebook on a free GPU cloud instance.

**Comment by Hyperparticle** [comment]
Yes, that is very slow, shouldn't take longer than an hour. If your system is using a GPU, then that probably means you have a bottleneck somewhere. Have you tried running other code with Keras, like one of their tutorials with GPU?

**Comment by tuji-sjp** [comment]
> Yes, that is very slow, shouldn't take longer than an hour. If your system is using a GPU, then that probably means you have a bottleneck somewhere. Have you tried running other code with Keras, like one of their tutorials with GPU?

Ok, I will continue to study the work. And I want to get a statistical success rate of 500 samples on ImageNet.
