### ISSUE TITLE
how can i calculate the value of success rate for target attack?

### ISSUE THREAD

**Issue by sumit429** [Hyperparticle/one-pixel-attack-keras#12]

**Comment by sumit429** [comment]
Hello, could you please tell me about how to calculate success rate for LeNet in case of targeted attack?
is there any formulas?
thanks!

**Comment by sumit429** [comment]
> _No description provided._

**Comment by Hyperparticle** [comment]
The success rate is simply the images that successfully fooled the network divided by the total number of attack images: `success_images / total_images`. The calculation is performed by `attack_stats()` inside `helper.py`.

**Comment by sumit429** [comment]
Thanks sir...
