### ISSUE TITLE
Getting a lot of adversarial images

### ISSUE THREAD

**Issue by moisbeug22** [Hyperparticle/one-pixel-attack-keras#14]
Hello everyone,

I am trying to fool the entire cifar10 data-set by using the one-pixel attack and download it for a project.
As I do not know how the attack function has been made, I will be glad to get help from someone.
I noticed that I can only fool one image per iteration. What I would do is to fool many image then download them.

Best regards

**Comment by Hyperparticle** [comment]
To be clear, you are trying to fool multiple images at the same time? The Differential Evolution algorithm is fundamentally iterative, which requires multiple passes before finding an adversarial version of each image. If you would like to save the adversarial images, you may modify the code to save [`attack_image` inside the `attack()` function in `attack.py`](https://github.com/Hyperparticle/one-pixel-attack-keras/blob/master/attack.py#L83).

**Comment by Hyperparticle** [comment]
Were you able to resolve the issue?

**Comment by moisbeug22** [comment]
Hello,
Sorry for the delay. I finally found a way to save the images I perturbed.

Thanks for your help

MB

Le jeu. 8 août 2019 à 05:16, Dan Kondratyuk <notifications@github.com> a
écrit :
