### ISSUE TITLE
Passing img instead of id

### ISSUE THREAD

**Issue by pniedzwiedzinski** [Hyperparticle/one-pixel-attack-keras#15]
Function `attack_success` takes argument `img` which is an id of the image in the dataset. Wouldn't it be clearer if this variable is called `img_id` or something like this? Or we could pass the whole image from the dataset instead.

**Comment by Hyperparticle** [comment]
Yes, I agree this could be clearer if it was either called `img_id` or passed in the image itself. Looking back, I notice that the `attack_success` function in `attack.py` actually does pass in the image, so I think I can modify the Jupyter notebook to be the same.

**Comment by Hyperparticle** [comment]
I refactored the code, should be good to go.
