### ISSUE TITLE
Bug on attack_all function

### ISSUE THREAD

**Issue by falcaopetri** [Hyperparticle/one-pixel-attack-keras#16]
The previous commit ae232d7 partially fixes some wrong attributes usages. One usage is still not fixed, and is triggered when calling `attack_all()` with `targeted=True`:

https://github.com/Hyperparticle/one-pixel-attack-keras/blob/13d2587e49e73e5d944d2a276de6a54300b103ae/attack.py#L114-L115

**Comment by Hyperparticle** [comment]
Thanks for the heads-up!
