### ISSUE TITLE
About image processing

### ISSUE THREAD

**Issue by tuji-sjp** [Hyperparticle/one-pixel-attack-keras#18]
Hello, I would like to ask why CIFAR-10 was not pre-processed in your code, while the image of ImageNet was pre-processed?
In addition, does the adversarial examples need to be pre-processed (such as normalization) before being fed into the model for reclassification?

**Comment by tuji-sjp** [comment]
Also, I'm not quite sure whether we are attacking the original image or the pre-processed image? There seems to be a contradiction in your code.
![微信截图_20191025223639](https://user-images.githubusercontent.com/30012354/67580501-09db9600-f779-11e9-84b5-0f58f65c6150.png)
![微信截图_20191025223603](https://user-images.githubusercontent.com/30012354/67580512-0d6f1d00-f779-11e9-9972-24d299c69f1b.png)

**Comment by Hyperparticle** [comment]
The CIFAR10 images are preprocessed, just using a different preprocessing function. Each network defines `color_process()`, which is called on every `predict()` for CIFAR images. E.g., https://github.com/Hyperparticle/one-pixel-attack-keras/blob/master/networks/resnet.py#L165.

The ImageNet notebook is experimental for now. It uses [`imagenet_utils`](https://github.com/keras-team/keras-applications/blob/master/keras_applications/imagenet_utils.py) to do the preprocessing instead. This is a more general approach for arbitrary images, but the code isn't finished here.

As for your final point, the first bit of code is simply a demonstration. If it was preprocessed, it would be hard to view it as an image. The actual attack, however, should use the preprocessed image, as in the second bit.

Hope that helps.

**Comment by tuji-sjp** [comment]
> The CIFAR10 images are preprocessed, just using a different preprocessing function. Each network defines `color_process()`, which is called on every `predict()` for CIFAR images. E.g., https://github.com/Hyperparticle/one-pixel-attack-keras/blob/master/networks/resnet.py#L165.
> 
> The ImageNet notebook is experimental for now. It uses [`imagenet_utils`](https://github.com/keras-team/keras-applications/blob/master/keras_applications/imagenet_utils.py) to do the preprocessing instead. This is a more general approach for arbitrary images, but the code isn't finished here.
> 
> As for your final point, the first bit of code is simply a demonstration. If it was preprocessed, it would be hard to view it as an image. The actual attack, however, should use the preprocessed image, as in the second bit.
> 
> Hope that helps.

Thank you very much. It helps me a lot!
