### ISSUE TITLE
The argument targeted

### ISSUE THREAD

**Issue by TudouJack** [Hyperparticle/one-pixel-attack-keras#19]
There is a argument，targeted，in the attack.py .

parser.add_argument('--targeted', action='store_false', help='Set this switch to test for targeted attacks.')

Please tell me,if the action = 'store_false',the attack is targeted or not?
Thank u for answering my issue.

**Comment by Hyperparticle** [comment]
By default, the attack will be untargeted. If you add `--targeted` to the command-line arguments, then it will be targeted.

The parser syntax can be a bit confusing, `action='store_false'`, just means it the variable will be false by default unless it's specified on the command-line.

**Comment by TudouJack** [comment]
> By default, the attack will be untargeted. If you add `--targeted` to the command-line arguments, then it will be targeted.
> 
> The parser syntax can be a bit confusing, `action='store_false'`, just means it the variable will be false by default unless it's specified on the command-line.

Oh，I got it. Thank you very much，your answer is pretty helpful.
