### ISSUE TITLE
How does the targeted attack work?

### ISSUE THREAD

**Issue by TudouJack** [Hyperparticle/one-pixel-attack-keras#20]
Hello:
I feel puzzled about that if just changing one pixel can implement the targeted attack. I think  only one-pixel change can not make the target that attacked with clear.
Please tell me how does the targeted attack work with so few pixel.
Thank you!

**Comment by Hyperparticle** [comment]
Targeted attack is much more difficult than untargeted, so it might be the case that you won't easily find a pixel in the image that will change the probability to the class of choice. However, it may be surprising that sometimes the attack succeeds. It's hard to know exactly why it's the case, it's still an active area of research.
