### ISSUE TITLE
how to fix RuntimeWarning: divide by zero encountered in double_scalars

### ISSUE THREAD

**Issue by LunarMaterial** [Hyperparticle/one-pixel-attack-keras#21]
using model lenet , when attacking it warns that "RuntimeWarning: divide by zero encountered in double_scalars" convergence=self.tol / convergence) is True): 
 it means covergence is zero? i dont know how to fix this please help me! 
the error is appears in  differential _evolution.py :585

**Comment by Hyperparticle** [comment]
That's quite odd, not sure why it would be zero. You can try to fix it by changing the line to `convergence=self.tol / (convergence + 1e-6)` so that the denominator is always nonzero.
