### ISSUE TITLE
How to display the picture after the attack？

### ISSUE THREAD

**Issue by lvhuanhuan123** [Hyperparticle/one-pixel-attack-keras#22]
Hello, after running attack.py, the pkl file is saved. I would like to ask how to display the image after the attack? Attack is to perturb a single pixel. Has the value of other pixels in the image changed? Thank you and look forward to your reply.

**Comment by TongSEU** [comment]
Have you solved this problem? I also want to know how to display the attacked pictures. Thank you!

**Comment by Hyperparticle** [comment]
Sorry, I've been busy. The [notebook/Colab](https://colab.research.google.com/drive/1Zq1kGP9C7i-70-SXyuEEaqYngtyQZMn7) should show you how to do this. More specifically, [helper.py](https://github.com/Hyperparticle/one-pixel-attack-keras/blob/master/helper.py) has a function called `plot_image` that you can use. The `attack` function in the Colab calls this helper function to display the attacked image.

Does this answer your question, or are you looking for something more specific?

**Comment by lvhuanhuan123** [comment]
Hello, I want to ask a question about the dataset. 
Here, "Attack on 1,3,5 pixel perturbations (100 samples)" refers to the result of an attack on 100 images randomly selected from the original cifar10 dataset?
Or is it the result of generating 100 adversarial images for each of the 10,000 images in the cifar10 test dataset? Thank you！

**Comment by MichaelTJC96** [comment]
can I download the pictures too?
