### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ghghgh0001** [Hyperparticle/one-pixel-attack-keras#6]
File "helper.py", line 32
    x_pos, y_pos, *rgb = pixel
                  ^
SyntaxError: invalid syntax
I met this problem while running the "imports" of "1_one-pixel-attack-cifar10", with both python2 and python3.

**Comment by ghghgh0001** [comment]
I deleted the "*" before the rgb, and it works, is it correct?

**Comment by Hyperparticle** [comment]
It seems that you're running a version of Python that does not support [Extended Iterable Unpacking](https://www.python.org/dev/peps/pep-3132/). According to [this StackOverflow post](https://stackoverflow.com/questions/16563623/invalid-syntax-python-starred-expressions), it should work with Python 3.0+.

Are you sure you are running with Python 3? There shouldn't be a syntax error in that case.

**Comment by ghghgh0001** [comment]
I changed the kernel of jupyter to python3, but it doesn't work, and I updated my jupyter, but it still no use.

x_pos, y_pos, r, g, b = pixel
img[x_pos, y_pos] = [r, g, b]

I write them like this, is it the same?

**Comment by ghghgh0001** [comment]
I change the kernal of jupyter to python3, but it still 2.7.12, seems something wrong with my jupyter. I copy the code to a .py file, and use python3 to open it in the terminal, and there's no problem now. Thanks for answering my silly problem. :)
