### ISSUE TITLE
AttributeError: 'DenseNet' object has no attribute '_model'

### ISSUE THREAD

**Issue by fxle** [Hyperparticle/one-pixel-attack-keras#8]
pylint E0401:unable to import 'keras.utils'
unable to import networks.capsulenet.capsule_net
 when i uesed ''python attack.py --model densenet capsnet'',the above problems appeared,Who can help me t how to solve it?tanks a lot

**Comment by Hyperparticle** [comment]
Did you make sure you have downloaded the `densenet.h5` and `capsnet.h5 ` models and put them in the `models` directory? Also, make sure you're running an up-to-date version of Keras.

**Comment by fxle** [comment]
But  I can't  find   the densenet.h5 and capsnet.h5 models .Can you provide me with this download link?Thank you  very much.

**Comment by Hyperparticle** [comment]
You can find the link in the Jupyter notebook, under the "Load Models" section.
https://www.dropbox.com/sh/dvatkpjl0sn79kn/AAC9L4puJ_sdFUkDZfr5SFkLa?dl=0

**Comment by Hyperparticle** [comment]
Have you solved your issue?

**Comment by fxle** [comment]
Yeah,Thank you for your concern. I have solved it and got the result.but how to show the results.pkl?

**Comment by Hyperparticle** [comment]
To show the `results.pkl`, you can use something like `helper.load_results()` and load the data into a Pandas `DataFrame`, as seen in the "Attack Statistics" section of the notebook.

**Comment by fxle** [comment]
Ok Thanks
