### ISSUE TITLE
How to use gpu in the model ?

### ISSUE THREAD

**Issue by lith0613** [Hyperparticle/one-pixel-attack-keras#9]
I try to use the gpu in the one-pixel attack for imagenet, because the model run on imagenet is too slow, but I use os.environ["CUDA_VISIBLE_DEVICES"] seems did not work, can you give some help. Thanks so much !

**Comment by Hyperparticle** [comment]
Did you run the code in the notebook to check if the GPU is enabled? You can also try [this StackOverflow post](https://stackoverflow.com/questions/38009682/how-to-tell-if-tensorflow-is-using-gpu-acceleration-from-inside-python-shell). If it's enabled for TensorFlow, it should be enabled for Keras.

**Comment by lith0613** [comment]
Thanks， I found I have just installed the cpu version tensorflow
